package com.yxst.mes.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yxst.mes.database.model.ItemValue;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ITEM_VALUE".
*/
public class ItemValueDao extends AbstractDao<ItemValue, Long> {

    public static final String TABLENAME = "ITEM_VALUE";

    /**
     * Properties of entity ItemValue.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property UserID = new Property(1, Long.class, "UserID", false, "USER_ID");
        public final static Property LineID = new Property(2, Long.class, "LineID", false, "LINE_ID");
        public final static Property EquipmentID = new Property(3, Long.class, "EquipmentID", false, "EQUIPMENT_ID");
        public final static Property PlaceID = new Property(4, Long.class, "PlaceID", false, "PLACE_ID");
        public final static Property ItemID = new Property(5, Long.class, "ItemID", false, "ITEM_ID");
        public final static Property BeginTime = new Property(6, java.util.Date.class, "BeginTime", false, "BEGIN_TIME");
        public final static Property EndTime = new Property(7, java.util.Date.class, "EndTime", false, "END_TIME");
        public final static Property CheckValue = new Property(8, String.class, "checkValue", false, "CHECK_VALUE");
        public final static Property InpsectStatus = new Property(9, int.class, "inpsectStatus", false, "INPSECT_STATUS");
    }


    public ItemValueDao(DaoConfig config) {
        super(config);
    }
    
    public ItemValueDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ITEM_VALUE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"USER_ID\" INTEGER," + // 1: UserID
                "\"LINE_ID\" INTEGER," + // 2: LineID
                "\"EQUIPMENT_ID\" INTEGER," + // 3: EquipmentID
                "\"PLACE_ID\" INTEGER," + // 4: PlaceID
                "\"ITEM_ID\" INTEGER," + // 5: ItemID
                "\"BEGIN_TIME\" INTEGER," + // 6: BeginTime
                "\"END_TIME\" INTEGER," + // 7: EndTime
                "\"CHECK_VALUE\" TEXT," + // 8: checkValue
                "\"INPSECT_STATUS\" INTEGER NOT NULL );"); // 9: inpsectStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ITEM_VALUE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ItemValue entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        Long UserID = entity.getUserID();
        if (UserID != null) {
            stmt.bindLong(2, UserID);
        }
 
        Long LineID = entity.getLineID();
        if (LineID != null) {
            stmt.bindLong(3, LineID);
        }
 
        Long EquipmentID = entity.getEquipmentID();
        if (EquipmentID != null) {
            stmt.bindLong(4, EquipmentID);
        }
 
        Long PlaceID = entity.getPlaceID();
        if (PlaceID != null) {
            stmt.bindLong(5, PlaceID);
        }
 
        Long ItemID = entity.getItemID();
        if (ItemID != null) {
            stmt.bindLong(6, ItemID);
        }
 
        java.util.Date BeginTime = entity.getBeginTime();
        if (BeginTime != null) {
            stmt.bindLong(7, BeginTime.getTime());
        }
 
        java.util.Date EndTime = entity.getEndTime();
        if (EndTime != null) {
            stmt.bindLong(8, EndTime.getTime());
        }
 
        String checkValue = entity.getCheckValue();
        if (checkValue != null) {
            stmt.bindString(9, checkValue);
        }
        stmt.bindLong(10, entity.getInpsectStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ItemValue entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        Long UserID = entity.getUserID();
        if (UserID != null) {
            stmt.bindLong(2, UserID);
        }
 
        Long LineID = entity.getLineID();
        if (LineID != null) {
            stmt.bindLong(3, LineID);
        }
 
        Long EquipmentID = entity.getEquipmentID();
        if (EquipmentID != null) {
            stmt.bindLong(4, EquipmentID);
        }
 
        Long PlaceID = entity.getPlaceID();
        if (PlaceID != null) {
            stmt.bindLong(5, PlaceID);
        }
 
        Long ItemID = entity.getItemID();
        if (ItemID != null) {
            stmt.bindLong(6, ItemID);
        }
 
        java.util.Date BeginTime = entity.getBeginTime();
        if (BeginTime != null) {
            stmt.bindLong(7, BeginTime.getTime());
        }
 
        java.util.Date EndTime = entity.getEndTime();
        if (EndTime != null) {
            stmt.bindLong(8, EndTime.getTime());
        }
 
        String checkValue = entity.getCheckValue();
        if (checkValue != null) {
            stmt.bindString(9, checkValue);
        }
        stmt.bindLong(10, entity.getInpsectStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ItemValue readEntity(Cursor cursor, int offset) {
        ItemValue entity = new ItemValue( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // UserID
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // LineID
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // EquipmentID
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // PlaceID
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // ItemID
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // BeginTime
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // EndTime
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // checkValue
            cursor.getInt(offset + 9) // inpsectStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ItemValue entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLineID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setEquipmentID(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setPlaceID(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setItemID(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setBeginTime(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setEndTime(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setCheckValue(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setInpsectStatus(cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ItemValue entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ItemValue entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ItemValue entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
