package com.yxst.mes.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yxst.mes.database.model.LubeDevice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LUBE_DEVICE".
*/
public class LubeDeviceDao extends AbstractDao<LubeDevice, Long> {

    public static final String TABLENAME = "LUBE_DEVICE";

    /**
     * Properties of entity LubeDevice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PlanID = new Property(1, Long.class, "PlanID", false, "PLAN_ID");
        public final static Property ZoneID = new Property(2, Long.class, "ZoneID", false, "ZONE_ID");
        public final static Property ZoneName = new Property(3, String.class, "ZoneName", false, "ZONE_NAME");
        public final static Property UserID = new Property(4, Long.class, "UserID", false, "USER_ID");
        public final static Property EquipmentID = new Property(5, Long.class, "EquipmentID", false, "EQUIPMENT_ID");
        public final static Property EquipmentName = new Property(6, String.class, "EquipmentName", false, "EQUIPMENT_NAME");
        public final static Property EquipmentModel = new Property(7, String.class, "EquipmentModel", false, "EQUIPMENT_MODEL");
        public final static Property BeginTime = new Property(8, java.util.Date.class, "BeginTime", false, "BEGIN_TIME");
        public final static Property EndTime = new Property(9, java.util.Date.class, "EndTime", false, "END_TIME");
    }


    public LubeDeviceDao(DaoConfig config) {
        super(config);
    }
    
    public LubeDeviceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LUBE_DEVICE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PLAN_ID\" INTEGER," + // 1: PlanID
                "\"ZONE_ID\" INTEGER," + // 2: ZoneID
                "\"ZONE_NAME\" TEXT," + // 3: ZoneName
                "\"USER_ID\" INTEGER," + // 4: UserID
                "\"EQUIPMENT_ID\" INTEGER," + // 5: EquipmentID
                "\"EQUIPMENT_NAME\" TEXT," + // 6: EquipmentName
                "\"EQUIPMENT_MODEL\" TEXT," + // 7: EquipmentModel
                "\"BEGIN_TIME\" INTEGER," + // 8: BeginTime
                "\"END_TIME\" INTEGER);"); // 9: EndTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LUBE_DEVICE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LubeDevice entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long PlanID = entity.getPlanID();
        if (PlanID != null) {
            stmt.bindLong(2, PlanID);
        }
 
        Long ZoneID = entity.getZoneID();
        if (ZoneID != null) {
            stmt.bindLong(3, ZoneID);
        }
 
        String ZoneName = entity.getZoneName();
        if (ZoneName != null) {
            stmt.bindString(4, ZoneName);
        }
 
        Long UserID = entity.getUserID();
        if (UserID != null) {
            stmt.bindLong(5, UserID);
        }
 
        Long EquipmentID = entity.getEquipmentID();
        if (EquipmentID != null) {
            stmt.bindLong(6, EquipmentID);
        }
 
        String EquipmentName = entity.getEquipmentName();
        if (EquipmentName != null) {
            stmt.bindString(7, EquipmentName);
        }
 
        String EquipmentModel = entity.getEquipmentModel();
        if (EquipmentModel != null) {
            stmt.bindString(8, EquipmentModel);
        }
 
        java.util.Date BeginTime = entity.getBeginTime();
        if (BeginTime != null) {
            stmt.bindLong(9, BeginTime.getTime());
        }
 
        java.util.Date EndTime = entity.getEndTime();
        if (EndTime != null) {
            stmt.bindLong(10, EndTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LubeDevice entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long PlanID = entity.getPlanID();
        if (PlanID != null) {
            stmt.bindLong(2, PlanID);
        }
 
        Long ZoneID = entity.getZoneID();
        if (ZoneID != null) {
            stmt.bindLong(3, ZoneID);
        }
 
        String ZoneName = entity.getZoneName();
        if (ZoneName != null) {
            stmt.bindString(4, ZoneName);
        }
 
        Long UserID = entity.getUserID();
        if (UserID != null) {
            stmt.bindLong(5, UserID);
        }
 
        Long EquipmentID = entity.getEquipmentID();
        if (EquipmentID != null) {
            stmt.bindLong(6, EquipmentID);
        }
 
        String EquipmentName = entity.getEquipmentName();
        if (EquipmentName != null) {
            stmt.bindString(7, EquipmentName);
        }
 
        String EquipmentModel = entity.getEquipmentModel();
        if (EquipmentModel != null) {
            stmt.bindString(8, EquipmentModel);
        }
 
        java.util.Date BeginTime = entity.getBeginTime();
        if (BeginTime != null) {
            stmt.bindLong(9, BeginTime.getTime());
        }
 
        java.util.Date EndTime = entity.getEndTime();
        if (EndTime != null) {
            stmt.bindLong(10, EndTime.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LubeDevice readEntity(Cursor cursor, int offset) {
        LubeDevice entity = new LubeDevice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // PlanID
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // ZoneID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ZoneName
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // UserID
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // EquipmentID
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // EquipmentName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // EquipmentModel
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // BeginTime
            cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)) // EndTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LubeDevice entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPlanID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setZoneID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setZoneName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUserID(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setEquipmentID(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setEquipmentName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEquipmentModel(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBeginTime(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setEndTime(cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LubeDevice entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LubeDevice entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LubeDevice entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
