package com.yxst.mes.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yxst.mes.database.model.Monitor;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MONITOR".
*/
public class MonitorDao extends AbstractDao<Monitor, Long> {

    public static final String TABLENAME = "MONITOR";

    /**
     * Properties of entity Monitor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MenuID = new Property(1, Long.class, "MenuID", false, "MENU_ID");
        public final static Property MenuNameCN = new Property(2, String.class, "MenuNameCN", false, "MENU_NAME_CN");
        public final static Property URL = new Property(3, String.class, "URL", false, "URL");
    }


    public MonitorDao(DaoConfig config) {
        super(config);
    }
    
    public MonitorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MONITOR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MENU_ID\" INTEGER," + // 1: MenuID
                "\"MENU_NAME_CN\" TEXT," + // 2: MenuNameCN
                "\"URL\" TEXT);"); // 3: URL
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MONITOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Monitor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long MenuID = entity.getMenuID();
        if (MenuID != null) {
            stmt.bindLong(2, MenuID);
        }
 
        String MenuNameCN = entity.getMenuNameCN();
        if (MenuNameCN != null) {
            stmt.bindString(3, MenuNameCN);
        }
 
        String URL = entity.getURL();
        if (URL != null) {
            stmt.bindString(4, URL);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Monitor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long MenuID = entity.getMenuID();
        if (MenuID != null) {
            stmt.bindLong(2, MenuID);
        }
 
        String MenuNameCN = entity.getMenuNameCN();
        if (MenuNameCN != null) {
            stmt.bindString(3, MenuNameCN);
        }
 
        String URL = entity.getURL();
        if (URL != null) {
            stmt.bindString(4, URL);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Monitor readEntity(Cursor cursor, int offset) {
        Monitor entity = new Monitor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // MenuID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // MenuNameCN
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // URL
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Monitor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMenuID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMenuNameCN(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setURL(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Monitor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Monitor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Monitor entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
