package com.yxst.inspect.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yxst.inspect.database.model.Cycle;
import com.yxst.inspect.database.model.Device;
import com.yxst.inspect.database.model.Grade;
import com.yxst.inspect.database.model.InspectDevice;
import com.yxst.inspect.database.model.InspectDeviceValue;
import com.yxst.inspect.database.model.InspectImage;
import com.yxst.inspect.database.model.InspectLine;
import com.yxst.inspect.database.model.Item;
import com.yxst.inspect.database.model.Line;
import com.yxst.inspect.database.model.LubeDevice;
import com.yxst.inspect.database.model.LubeImage;
import com.yxst.inspect.database.model.LubeItem;
import com.yxst.inspect.database.model.Monitor;
import com.yxst.inspect.database.model.Place;
import com.yxst.inspect.database.model.Plan;
import com.yxst.inspect.database.model.Record;
import com.yxst.inspect.database.model.Sample;
import com.yxst.inspect.database.model.Undetect;
import com.yxst.inspect.database.model.UnLube;
import com.yxst.inspect.database.model.User;

import com.yxst.inspect.database.dao.CycleDao;
import com.yxst.inspect.database.dao.DeviceDao;
import com.yxst.inspect.database.dao.GradeDao;
import com.yxst.inspect.database.dao.InspectDeviceDao;
import com.yxst.inspect.database.dao.InspectDeviceValueDao;
import com.yxst.inspect.database.dao.InspectImageDao;
import com.yxst.inspect.database.dao.InspectLineDao;
import com.yxst.inspect.database.dao.ItemDao;
import com.yxst.inspect.database.dao.LineDao;
import com.yxst.inspect.database.dao.LubeDeviceDao;
import com.yxst.inspect.database.dao.LubeImageDao;
import com.yxst.inspect.database.dao.LubeItemDao;
import com.yxst.inspect.database.dao.MonitorDao;
import com.yxst.inspect.database.dao.PlaceDao;
import com.yxst.inspect.database.dao.PlanDao;
import com.yxst.inspect.database.dao.RecordDao;
import com.yxst.inspect.database.dao.SampleDao;
import com.yxst.inspect.database.dao.UndetectDao;
import com.yxst.inspect.database.dao.UnLubeDao;
import com.yxst.inspect.database.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cycleDaoConfig;
    private final DaoConfig deviceDaoConfig;
    private final DaoConfig gradeDaoConfig;
    private final DaoConfig inspectDeviceDaoConfig;
    private final DaoConfig inspectDeviceValueDaoConfig;
    private final DaoConfig inspectImageDaoConfig;
    private final DaoConfig inspectLineDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig lineDaoConfig;
    private final DaoConfig lubeDeviceDaoConfig;
    private final DaoConfig lubeImageDaoConfig;
    private final DaoConfig lubeItemDaoConfig;
    private final DaoConfig monitorDaoConfig;
    private final DaoConfig placeDaoConfig;
    private final DaoConfig planDaoConfig;
    private final DaoConfig recordDaoConfig;
    private final DaoConfig sampleDaoConfig;
    private final DaoConfig undetectDaoConfig;
    private final DaoConfig unLubeDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CycleDao cycleDao;
    private final DeviceDao deviceDao;
    private final GradeDao gradeDao;
    private final InspectDeviceDao inspectDeviceDao;
    private final InspectDeviceValueDao inspectDeviceValueDao;
    private final InspectImageDao inspectImageDao;
    private final InspectLineDao inspectLineDao;
    private final ItemDao itemDao;
    private final LineDao lineDao;
    private final LubeDeviceDao lubeDeviceDao;
    private final LubeImageDao lubeImageDao;
    private final LubeItemDao lubeItemDao;
    private final MonitorDao monitorDao;
    private final PlaceDao placeDao;
    private final PlanDao planDao;
    private final RecordDao recordDao;
    private final SampleDao sampleDao;
    private final UndetectDao undetectDao;
    private final UnLubeDao unLubeDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cycleDaoConfig = daoConfigMap.get(CycleDao.class).clone();
        cycleDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        gradeDaoConfig = daoConfigMap.get(GradeDao.class).clone();
        gradeDaoConfig.initIdentityScope(type);

        inspectDeviceDaoConfig = daoConfigMap.get(InspectDeviceDao.class).clone();
        inspectDeviceDaoConfig.initIdentityScope(type);

        inspectDeviceValueDaoConfig = daoConfigMap.get(InspectDeviceValueDao.class).clone();
        inspectDeviceValueDaoConfig.initIdentityScope(type);

        inspectImageDaoConfig = daoConfigMap.get(InspectImageDao.class).clone();
        inspectImageDaoConfig.initIdentityScope(type);

        inspectLineDaoConfig = daoConfigMap.get(InspectLineDao.class).clone();
        inspectLineDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        lineDaoConfig = daoConfigMap.get(LineDao.class).clone();
        lineDaoConfig.initIdentityScope(type);

        lubeDeviceDaoConfig = daoConfigMap.get(LubeDeviceDao.class).clone();
        lubeDeviceDaoConfig.initIdentityScope(type);

        lubeImageDaoConfig = daoConfigMap.get(LubeImageDao.class).clone();
        lubeImageDaoConfig.initIdentityScope(type);

        lubeItemDaoConfig = daoConfigMap.get(LubeItemDao.class).clone();
        lubeItemDaoConfig.initIdentityScope(type);

        monitorDaoConfig = daoConfigMap.get(MonitorDao.class).clone();
        monitorDaoConfig.initIdentityScope(type);

        placeDaoConfig = daoConfigMap.get(PlaceDao.class).clone();
        placeDaoConfig.initIdentityScope(type);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        sampleDaoConfig = daoConfigMap.get(SampleDao.class).clone();
        sampleDaoConfig.initIdentityScope(type);

        undetectDaoConfig = daoConfigMap.get(UndetectDao.class).clone();
        undetectDaoConfig.initIdentityScope(type);

        unLubeDaoConfig = daoConfigMap.get(UnLubeDao.class).clone();
        unLubeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cycleDao = new CycleDao(cycleDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);
        gradeDao = new GradeDao(gradeDaoConfig, this);
        inspectDeviceDao = new InspectDeviceDao(inspectDeviceDaoConfig, this);
        inspectDeviceValueDao = new InspectDeviceValueDao(inspectDeviceValueDaoConfig, this);
        inspectImageDao = new InspectImageDao(inspectImageDaoConfig, this);
        inspectLineDao = new InspectLineDao(inspectLineDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        lineDao = new LineDao(lineDaoConfig, this);
        lubeDeviceDao = new LubeDeviceDao(lubeDeviceDaoConfig, this);
        lubeImageDao = new LubeImageDao(lubeImageDaoConfig, this);
        lubeItemDao = new LubeItemDao(lubeItemDaoConfig, this);
        monitorDao = new MonitorDao(monitorDaoConfig, this);
        placeDao = new PlaceDao(placeDaoConfig, this);
        planDao = new PlanDao(planDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);
        sampleDao = new SampleDao(sampleDaoConfig, this);
        undetectDao = new UndetectDao(undetectDaoConfig, this);
        unLubeDao = new UnLubeDao(unLubeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Cycle.class, cycleDao);
        registerDao(Device.class, deviceDao);
        registerDao(Grade.class, gradeDao);
        registerDao(InspectDevice.class, inspectDeviceDao);
        registerDao(InspectDeviceValue.class, inspectDeviceValueDao);
        registerDao(InspectImage.class, inspectImageDao);
        registerDao(InspectLine.class, inspectLineDao);
        registerDao(Item.class, itemDao);
        registerDao(Line.class, lineDao);
        registerDao(LubeDevice.class, lubeDeviceDao);
        registerDao(LubeImage.class, lubeImageDao);
        registerDao(LubeItem.class, lubeItemDao);
        registerDao(Monitor.class, monitorDao);
        registerDao(Place.class, placeDao);
        registerDao(Plan.class, planDao);
        registerDao(Record.class, recordDao);
        registerDao(Sample.class, sampleDao);
        registerDao(Undetect.class, undetectDao);
        registerDao(UnLube.class, unLubeDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        cycleDaoConfig.clearIdentityScope();
        deviceDaoConfig.clearIdentityScope();
        gradeDaoConfig.clearIdentityScope();
        inspectDeviceDaoConfig.clearIdentityScope();
        inspectDeviceValueDaoConfig.clearIdentityScope();
        inspectImageDaoConfig.clearIdentityScope();
        inspectLineDaoConfig.clearIdentityScope();
        itemDaoConfig.clearIdentityScope();
        lineDaoConfig.clearIdentityScope();
        lubeDeviceDaoConfig.clearIdentityScope();
        lubeImageDaoConfig.clearIdentityScope();
        lubeItemDaoConfig.clearIdentityScope();
        monitorDaoConfig.clearIdentityScope();
        placeDaoConfig.clearIdentityScope();
        planDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
        sampleDaoConfig.clearIdentityScope();
        undetectDaoConfig.clearIdentityScope();
        unLubeDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CycleDao getCycleDao() {
        return cycleDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public GradeDao getGradeDao() {
        return gradeDao;
    }

    public InspectDeviceDao getInspectDeviceDao() {
        return inspectDeviceDao;
    }

    public InspectDeviceValueDao getInspectDeviceValueDao() {
        return inspectDeviceValueDao;
    }

    public InspectImageDao getInspectImageDao() {
        return inspectImageDao;
    }

    public InspectLineDao getInspectLineDao() {
        return inspectLineDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public LineDao getLineDao() {
        return lineDao;
    }

    public LubeDeviceDao getLubeDeviceDao() {
        return lubeDeviceDao;
    }

    public LubeImageDao getLubeImageDao() {
        return lubeImageDao;
    }

    public LubeItemDao getLubeItemDao() {
        return lubeItemDao;
    }

    public MonitorDao getMonitorDao() {
        return monitorDao;
    }

    public PlaceDao getPlaceDao() {
        return placeDao;
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public SampleDao getSampleDao() {
        return sampleDao;
    }

    public UndetectDao getUndetectDao() {
        return undetectDao;
    }

    public UnLubeDao getUnLubeDao() {
        return unLubeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
