package com.yxst.inspect.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yxst.inspect.database.model.Device;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEVICE".
*/
public class DeviceDao extends AbstractDao<Device, Long> {

    public static final String TABLENAME = "DEVICE";

    /**
     * Properties of entity Device.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EquipmentID = new Property(1, Long.class, "EquipmentID", false, "EQUIPMENT_ID");
        public final static Property EquipmentCode = new Property(2, String.class, "EquipmentCode", false, "EQUIPMENT_CODE");
        public final static Property EquipmentName = new Property(3, String.class, "EquipmentName", false, "EQUIPMENT_NAME");
        public final static Property EquipmentModel = new Property(4, String.class, "EquipmentModel", false, "EQUIPMENT_MODEL");
        public final static Property RFID = new Property(5, String.class, "RFID", false, "RFID");
        public final static Property InspectStatus = new Property(6, int.class, "inspectStatus", false, "INSPECT_STATUS");
        public final static Property LineID = new Property(7, Long.class, "LineID", false, "LINE_ID");
    }

    private DaoSession daoSession;


    public DeviceDao(DaoConfig config) {
        super(config);
    }
    
    public DeviceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEVICE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"EQUIPMENT_ID\" INTEGER," + // 1: EquipmentID
                "\"EQUIPMENT_CODE\" TEXT," + // 2: EquipmentCode
                "\"EQUIPMENT_NAME\" TEXT," + // 3: EquipmentName
                "\"EQUIPMENT_MODEL\" TEXT," + // 4: EquipmentModel
                "\"RFID\" TEXT," + // 5: RFID
                "\"INSPECT_STATUS\" INTEGER NOT NULL ," + // 6: inspectStatus
                "\"LINE_ID\" INTEGER);"); // 7: LineID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEVICE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Device entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long EquipmentID = entity.getEquipmentID();
        if (EquipmentID != null) {
            stmt.bindLong(2, EquipmentID);
        }
 
        String EquipmentCode = entity.getEquipmentCode();
        if (EquipmentCode != null) {
            stmt.bindString(3, EquipmentCode);
        }
 
        String EquipmentName = entity.getEquipmentName();
        if (EquipmentName != null) {
            stmt.bindString(4, EquipmentName);
        }
 
        String EquipmentModel = entity.getEquipmentModel();
        if (EquipmentModel != null) {
            stmt.bindString(5, EquipmentModel);
        }
 
        String RFID = entity.getRFID();
        if (RFID != null) {
            stmt.bindString(6, RFID);
        }
        stmt.bindLong(7, entity.getInspectStatus());
 
        Long LineID = entity.getLineID();
        if (LineID != null) {
            stmt.bindLong(8, LineID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Device entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long EquipmentID = entity.getEquipmentID();
        if (EquipmentID != null) {
            stmt.bindLong(2, EquipmentID);
        }
 
        String EquipmentCode = entity.getEquipmentCode();
        if (EquipmentCode != null) {
            stmt.bindString(3, EquipmentCode);
        }
 
        String EquipmentName = entity.getEquipmentName();
        if (EquipmentName != null) {
            stmt.bindString(4, EquipmentName);
        }
 
        String EquipmentModel = entity.getEquipmentModel();
        if (EquipmentModel != null) {
            stmt.bindString(5, EquipmentModel);
        }
 
        String RFID = entity.getRFID();
        if (RFID != null) {
            stmt.bindString(6, RFID);
        }
        stmt.bindLong(7, entity.getInspectStatus());
 
        Long LineID = entity.getLineID();
        if (LineID != null) {
            stmt.bindLong(8, LineID);
        }
    }

    @Override
    protected final void attachEntity(Device entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Device readEntity(Cursor cursor, int offset) {
        Device entity = new Device( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // EquipmentID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // EquipmentCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // EquipmentName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // EquipmentModel
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // RFID
            cursor.getInt(offset + 6), // inspectStatus
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // LineID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Device entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEquipmentID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setEquipmentCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEquipmentName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEquipmentModel(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRFID(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setInspectStatus(cursor.getInt(offset + 6));
        entity.setLineID(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Device entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Device entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Device entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
